// <auto-generated />
using System;
using ContribuyentesDGII.Data.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContribuyentesDGII.Data.Migrations
{
    [DbContext(typeof(ContribuyentesDbContext))]
    partial class ContribuyentesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ContribuyentesDGII.Core.Models.ComprobanteFiscal", b =>
                {
                    b.Property<string>("NCF")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<decimal>("Itbis18")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RncCedula")
                        .HasMaxLength(11)
                        .HasColumnType("int");

                    b.Property<DateTime>("UltimaFechaModificacion")
                        .HasColumnType("datetime");

                    b.HasKey("NCF");

                    b.HasIndex("RncCedula");

                    b.ToTable("ComprobantesFiscales", (string)null);
                });

            modelBuilder.Entity("ContribuyentesDGII.Core.Models.Contribuyente", b =>
                {
                    b.Property<int>("RncCedula")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(11)
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RncCedula"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<short>("IdEstatus")
                        .HasColumnType("smallint");

                    b.Property<short>("IdTipoPersona")
                        .HasColumnType("smallint");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UltimaFechaModificacion")
                        .HasColumnType("datetime");

                    b.HasKey("RncCedula");

                    b.HasIndex("IdEstatus");

                    b.HasIndex("IdTipoPersona");

                    b.ToTable("Contribuyentes", (string)null);
                });

            modelBuilder.Entity("ContribuyentesDGII.Core.Models.Estatus", b =>
                {
                    b.Property<short>("IdEstatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("IdEstatus"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("UltimaFechaModificacion")
                        .HasColumnType("datetime");

                    b.HasKey("IdEstatus");

                    b.ToTable("Estatus", (string)null);
                });

            modelBuilder.Entity("ContribuyentesDGII.Core.Models.TipoPersona", b =>
                {
                    b.Property<short>("IdTipoPersona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("IdTipoPersona"));

                    b.Property<string>("DescripcionPersona")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("UltimaFechaModificacion")
                        .HasColumnType("datetime");

                    b.HasKey("IdTipoPersona");

                    b.ToTable("TipoPersonas", (string)null);
                });

            modelBuilder.Entity("ContribuyentesDGII.Core.Models.ComprobanteFiscal", b =>
                {
                    b.HasOne("ContribuyentesDGII.Core.Models.Contribuyente", "Contribuyente")
                        .WithMany("Comprobantes")
                        .HasForeignKey("RncCedula")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ComprobantesFiscales_Contribuyentes");

                    b.Navigation("Contribuyente");
                });

            modelBuilder.Entity("ContribuyentesDGII.Core.Models.Contribuyente", b =>
                {
                    b.HasOne("ContribuyentesDGII.Core.Models.Estatus", "Estatus")
                        .WithMany("Contribuyentes")
                        .HasForeignKey("IdEstatus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Contribuyentes_Estatus");

                    b.HasOne("ContribuyentesDGII.Core.Models.TipoPersona", "Tipo")
                        .WithMany("Contribuyentes")
                        .HasForeignKey("IdTipoPersona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Contribuyentes_TipoPersonas");

                    b.Navigation("Estatus");

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("ContribuyentesDGII.Core.Models.Contribuyente", b =>
                {
                    b.Navigation("Comprobantes");
                });

            modelBuilder.Entity("ContribuyentesDGII.Core.Models.Estatus", b =>
                {
                    b.Navigation("Contribuyentes");
                });

            modelBuilder.Entity("ContribuyentesDGII.Core.Models.TipoPersona", b =>
                {
                    b.Navigation("Contribuyentes");
                });
#pragma warning restore 612, 618
        }
    }
}
